name: text_sns
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_flavor: ^3.1.3
  flutter_flavorizr: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: "Text SNS Dev"
      android:
        applicationId: "com.firebaseapp.text_sns_dev_196e3"
      ios:
        bundleId: "com.firebaseapp.textSnsDev196e3"
    prod:
      app:
        name: "Text SNS"
      android:
        applicationId: "com.firebaseapp.text_sns_prod_47784"
      ios:
        bundleId: "com.firebaseapp.textSnsProd47784"

